version: '3'
services: 
    kong:
        image: kong:3.1.1-alpine
        command: "kong migrations bootstrap"
        container_name: kong
        environment: 
            KONG_DATABASE: postgres
            KONG_PG_HOST: postgres
            KONG_PG_PORT: 5432
            KONG_PG_USER: postgres
            KONG_PG_PASSWORD: mysecretpassword
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt
        ports: 
            - 80:8000
            - 443:8443
            - 127.0.0.1:8001:8001
        restart: always
        depends_on: 
            - postgres
    postgres:
        image: postgres:11.8
        container_name: kong-database
        ports: 
            - 8000:8000
        environment:
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: mysecretpassword
        restart: always
        volumes: 
            - "./postgres-vol:/var/lib/postgresql/data"
    konga:
        image: pantsel/konga
        container_name: konga
        environment: 
            NODE_ENV: production
        restart: always
        ports: 
            - 1337:1337
        volumes: 
            - ./konga-vol:/app/kongadata
