version: '3.1'
services:
  db:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: UborrowUV.01
      MYSQL_USER: AdminSite
      MYSQL_PASSWORD: UborrowUV.01
      MYSQL_DATABASE: DatabaseUBU
    ports:
      - "3307:3307"
    volumes:
      - "mysqldata:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  mysqldata: