# Generated by Django 4.1.5 on 2023-01-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listfromrec',
            old_name='username',
            new_name='user',
        ),
    ]
