# Generated by Django 4.1.5 on 2023-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_loandurable_idcart_alter_loanparcel_idcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandurable',
            old_name='idcart',
            new_name='id_borrow',
        ),
        migrations.RenameField(
            model_name='loanparcel',
            old_name='idcart',
            new_name='id_borrow',
        ),
        migrations.AddField(
            model_name='listfromrec',
            name='id_borrow',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
