# Generated by Django 4.1.5 on 2023-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_idcart_loandurable_id_borrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdurable',
            name='borrow_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cartparcel',
            name='borrow_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
