# Generated by Django 4.1.5 on 2023-01-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cartdurable_borrow_id_cartparcel_borrow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdurable',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='cartparcel',
            name='borrow_id',
        ),
        migrations.RemoveField(
            model_name='listfromrec',
            name='id_borrow',
        ),
        migrations.RemoveField(
            model_name='loandurable',
            name='id_borrow',
        ),
        migrations.RemoveField(
            model_name='loanparcel',
            name='id_borrow',
        ),
    ]
