# Generated by Django 4.1.5 on 2023-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_cartdurable_borrow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartparcel',
            name='code_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loanparcel',
            name='code_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
