# Generated by Django 4.1.5 on 2023-01-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cartparcel_code_number_loanparcel_code_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartparcel',
            name='code_number',
        ),
        migrations.RemoveField(
            model_name='loanparcel',
            name='code_number',
        ),
    ]
